services:
  - type: web
    name: our-family-tree
    env: node
    buildCommand: npm install
    startCommand: npm start
    buildFilter:
      paths:
        - package.json
        - package-lock.json
